#version: "3.9" obsolete
services:
  db:
    image: postgres:16
    container_name: mycookbook-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mycookbook}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mycookbook}
      POSTGRES_DB: ${POSTGRES_DB:-mycookbook}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mycookbook} -d ${POSTGRES_DB:-mycookbook}"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: mycookbook-pgadmin
    depends_on: [db]
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  pgdata:
